server:
  port: 80
zuul:
  routes:
    trainings:
      path: /trainings-management/**
      serviceId: trainings-service
    calculator:
      path: /calculator-management/**
      serviceId: calculator-service

spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url.default: http://localhost:8761/eureka
